name: Build Validation

on: pull_request

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 7

      - name: Install dependencies
        run: pnpm install

      - name: Rewrite titles
        run: pnpm run rewrite-title

      - name: Build
        run: pnpm run build
