name: Sync

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - uses: actions/setup-node@v3
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 7

      - uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - if: steps.pnpm-cache.outputs.cache-hit != 'true'
        run: pnpm install

      - name: Run sync script
        run: pnpm run sync ${{ secrets.GITHUB_TOKEN }}
